
apiVersion: v2
name: kubedash
description: "KubeDash is a general purpose, web-based UI for Kubernetes clusters."
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.19.x-0"
keywords:
  - kubedash
  - kubernetes dashboard
  - trivy-operator
home: https://github.com/devopstales/kubedash
icon: https://raw.githubusercontent.com/devopstales/helm-charts/main/icons/kubectl-login.png
sources:
  - https://github.com/devopstales/kubedash
  - https://github.com/devopstales/helm-charts
deprecated: false

dependencies:
- name: postgresql-ha
  version: "15.4.0"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresqlha.enabled